
server:
  port: 7878
  tomcat:
    threads:
      max: 4

luminous:
  node:
    name: ${ENV_NODE_NAME}
    description: ${ENV_NODE_DESCRIPTION}
    uniqueId: ${ENV_NODE_UNIQUE_ID}
    authorizationToken: ${ENV_NODE_AUTHORIZATION_TOKEN}
    hostname: ${ENV_NODE_HOSTNAME}
  version: 0.0.1
  platform: ${ENV_PLATFORM}